### ISSUE TITLE
Change IpFilter to inherit from AuthorizationFilterAttribute

### ISSUE THREAD

**Issue by stevenaw** [climax-media/climax-web-http#29]
It currently inherits from AuthorizeAttribute, which itself inherits from AuthorizationFilterAttribute. However, AuthorizeAttribute has some internal logic to only apply the filter if "AllowAnonymous" attribute is not on the filter. I believe this to be a mixing of concerns. We can't disambiguate the "who" from the "where".

Having IpFilter inherit from AuthorizationFilterAttribute would allow these to be handled distinctly, allowing more granularity. We can allow/deny access based on "who" and "where from" independently. 

Example: Someone may only want to allow access to certain resources, from certain other resources, using a specific authorization scheme or set of credentials.

NOTE: This would be a breaking change
Thoughts?

**Comment by filipw** [comment]
I think this is a very good idea. 

BTW I'd suggest to use a 403 response status code instead of the currently used [401](https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/System.Web.Http/AuthorizeAttribute.cs#L155), as semantically it would be much more applicable.

401 means we don’t know who you are, please authenticate and come back, and we will try to process the request for you again. 
403 means that the server refuses to fulfil the request - you may even be authenticated FWIW, but it doesn't matter. A 403 issued from the server is a de facto instruction to the caller "don’t call that endpoint again".

**Comment by stevenaw** [comment]
Nice, good idea @filipw

**Comment by stevenaw** [comment]
Closing as `wont do`. This can be re-opened if we do.
